react router
VelzckC0D3/math_magicians_react pull request #6
Opened 2023-05-05 20:25 UTC by VelzckC0D3

# Math Magicians -  `React` `ES6` `API`

## ✨ _Requested Implementations_ ✨
✔️ _Created a website that have 3 pages: `Home`, `Calculator` & `Quote`_
✔️ _Followed general layout_
✔️ _Added my own style to improve the look and feel_
✔️ _Every page has its own `Route`_
✔️ _**The navigation links to all 3 `Routes`** & they are displayed correctly_
✔️ _Used React Router to make the routes work_

#  💡 _Thank you for your review!_ 💡

2023-05-05 22:00 UTC, VelzckC0D3 commented
✨ Please note that the linters that are failed are the ones from Netlify, but the linters from the Workflow are working correctly, also, it says that it's failed but the Netlifty deploy is ok ✨
[Netlify Deploy](https://velzck-magician.netlify.app/)

2023-05-05 23:03 UTC, Tufahel requested changes
# Status: Required Changes :recycle:
Hi @VelzckC0D3 :wave:  

Good job so far! 👍 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights 🌟

![Alt Text](https://c.tenor.com/vOLW_UQMySIAAAAC/almost-there.gif)

✔️ Professional pull request
✔️ Correct Git-flow
✔️ Linter checks are passing
✔️ App is working fine
✔️ Awesome UI design.

## Required Changes ♻️

***Please kindly check the comments below.***

## Optional suggestions 🤷‍♂️

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-05 23:03 UTC, Tufahel commented on src/App.js
> +        </div>
![image](https://user-images.githubusercontent.com/60083437/236582023-5041c267-6aef-4c32-a14a-23d04e607b0f.png)
- As per the project requirements `the general layout should match with the wireframe`. In the wirefram wireframe the `title` should be aligned with the navigation `menu`.
![image](https://user-images.githubusercontent.com/60083437/236582123-664e491a-4fb6-489d-a3b6-d4dd5653ae30.png)
- But I can see you have added this below the navigation `menu`.
- I recommend you use it inside the `Navbar.js` and align it with the menu as per the given wireframe.
- [ ] Kindly fix this issue.

2023-05-06 00:23 UTC, VelzckC0D3 commented on src/App.js
> +        </div>
Done!, thank you @Tufahel

2023-05-06 00:32 UTC, Tufahel approved these changes
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:

Hi @VelzckC0D3 :wave: 
 
Well done on implementing all of the changes! 👍  Your project is complete now!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 👏🏻

![](https://media0.giphy.com/media/d31w24psGYeekCZy/giphy.gif?cid=ecf05e47zaer8jfqmid0gfxhz2oq4gcjqy2c2aol3ldn6gvl&rid=giphy.gif&ct=g)

:heavy_check_mark: Linter checks are passing.
:heavy_check_mark: Descriptive pull request.
:heavy_check_mark: UI looks great.
:heavy_check_mark: Correct Git-flow.

## Optional suggestions 🤷‍♂️

- [ ] Kindly use the capital letter as the first letter of the commit message as it is professional and looks smart.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.
- You can mail me at [![Mail](https://img.shields.io/badge/Gmail-tufahel96@gmail.com-red?logo=Gmail&logoColor=red&labelColor=black)](mailto:tufahel96@gmail.com) or ask any question at Slack, `Name: Tufahel`

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-06 00:34 UTC, merged